name: Build and push Ollama Docker image

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: delete user
        run: |
          sed -i "/USER/d" Dockerfile
          sed -i "/GROUP/d" Dockerfile

      # Runs a single command using the runners shell
      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: './Dockerfile'
          platforms: linux/amd64
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ollama:latest
            ghcr.io/${{ github.repository_owner }}/ollama:latest
